export interface Reserva {
    nombre: string,
    apellidos?: string,
    telefono: string,
    fechainicio: Date,
    fechafin: Date,
    idHabitacion: string,
    numeropersonas: number,
    numeroadultos: number,
    numeroninos: number,
    estado: string,
    metodoPago?: string,
    pagoVerificado?: boolean,
    precioTotal?: number,
    noches?: number,
    checkInEstado?: 'pendiente' | 'generado' | 'checkin' | 'checkout',
    checkInQrToken?: string,
    digitalKey?: string,
    checkInAt?: Date | null,
    checkOutAt?: Date | null,
    _id?: string
}